# Generated by Django 3.1.3 on 2020-12-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20201209_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='voter',
            name='secure_pin',
            field=models.PositiveIntegerField(),
        ),
    ]
