# Generated by Django 3.1.3 on 2020-12-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20201210_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='secure_pin',
        ),
    ]
