# Generated by Django 3.1.3 on 2020-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20201210_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='secure_pin',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
